services:
  - type: web
    name: arc-autonomous-risk-coverage
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
