services:
  - type: web
    name: arc-autonomous-risk-coverage
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app --chdir backend --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
